 export default class BriefData {
    email: string;
    companyName: string
    companyInfo: string;
    isFirstProject: string;
    personName: string;
    isWorkedWithOtherAgencies: string;
    whatPreferredAndNot: string;
    isOneTimeOrContinuous: string;
    criteriesOfWorkersChoosing: string;
    contactPerson: string;
    whoWillTakeDecisions: string;
    mainFunctionality: string;
    whatProblemsProductSolves: string;
    productAuditory: string;
    platform: string;
    isDocumentationAvailable: string;
    links: string;
    whatOsSupporting: string;
    linksToExistingExamples: string;
    linkExampleProsAndCons: string;
    ourProductAdvantages: string;
    isDesignFromScratch: string;
    isAppWillRunBackgroundSounds: string;
    isAppWillMultilingual: string;
    isMonetization: string;
    isServerPartAdminPanel: string;
    ifIsServerPartAdminIsBackend: string;
    screenOrientation: string;
    helpWithPublication: string;
    developmentStart: string;
    relizeDate: string;
    budget: string;
    other: string;
}